// <auto-generated />
namespace club.soundyard.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddAgreementToRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAgreementToRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202409231551388_AddAgreementToRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
